### ISSUE TITLE
Proyecto Capstone - Propuesta

### ISSUE THREAD

**Issue by Ernesto-Carrillo** [PalomaVilchis/CapstoneProject_UAM2021#7]
Hola Paloma, te comparto por este medio el enlace a nuestra propuesta de proyecto. Recibe un cordial saludo.

[https://github.com/Ernesto-Carrillo/CapstoneProject/blob/f6bd2aa6824d1ed77e36c85363094668afa0d6fa/Sistema%20IoT%20para%20monitorizar%20la%20calidad%20del%20agua%20empleando%20geoposicionamiento%20e%20inmersi%C3%B3n%20de%20sensores.pdf](url)

**Comment by PalomaVilchis** [comment]
Hola Carlos, No puedo ver el archivo
